nav:
  - Homepage: index.md
  - ZJU Courses:
    - Overview: ZJU_courses/ZJU_courses_profile.md
    - 24-25夏 常微分方程（1学分）: ZJU_courses/24-25_Summer_ODE_Chuanhou_Gao.md
  - Courses Notes:
    - CS61A-2022Fall: courses/Berkeley-CS61A-2022Fall.md
  - Projects:
    - 基于pyautogui的慧学外语Etalk自动实现: projects/基于pyautogui的慧学外语Etalk自动实现.md
  - To be classified:
      - About me: about.md